# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/glossary.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'app/glossary.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x61pp/glossary.proto\x12\x08glossary\"\x07\n\x05\x45mpty\"!\n\x0eKeywordRequest\x12\x0f\n\x07keyword\x18\x01 \x01(\t\"!\n\x0e\x44\x65leteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\",\n\x04Term\x12\x0f\n\x07keyword\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\")\n\x08TermList\x12\x1d\n\x05terms\x18\x01 \x03(\x0b\x32\x0e.glossary.Term2\x92\x02\n\x0fGlossaryService\x12/\n\x08GetTerms\x12\x0f.glossary.Empty\x1a\x12.glossary.TermList\x12\x33\n\x07GetTerm\x12\x18.glossary.KeywordRequest\x1a\x0e.glossary.Term\x12)\n\x07\x41\x64\x64Term\x12\x0e.glossary.Term\x1a\x0e.glossary.Term\x12,\n\nUpdateTerm\x12\x0e.glossary.Term\x1a\x0e.glossary.Term\x12@\n\nDeleteTerm\x12\x18.glossary.KeywordRequest\x1a\x18.glossary.DeleteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.glossary_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=32
  _globals['_EMPTY']._serialized_end=39
  _globals['_KEYWORDREQUEST']._serialized_start=41
  _globals['_KEYWORDREQUEST']._serialized_end=74
  _globals['_DELETERESPONSE']._serialized_start=76
  _globals['_DELETERESPONSE']._serialized_end=109
  _globals['_TERM']._serialized_start=111
  _globals['_TERM']._serialized_end=155
  _globals['_TERMLIST']._serialized_start=157
  _globals['_TERMLIST']._serialized_end=198
  _globals['_GLOSSARYSERVICE']._serialized_start=201
  _globals['_GLOSSARYSERVICE']._serialized_end=475
# @@protoc_insertion_point(module_scope)
