# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app import glossary_pb2 as app_dot_glossary__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in app/glossary_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GlossaryServiceStub(object):
    """Определение сервиса глоссария
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTerms = channel.unary_unary(
                '/glossary.GlossaryService/GetTerms',
                request_serializer=app_dot_glossary__pb2.Empty.SerializeToString,
                response_deserializer=app_dot_glossary__pb2.TermList.FromString,
                _registered_method=True)
        self.GetTerm = channel.unary_unary(
                '/glossary.GlossaryService/GetTerm',
                request_serializer=app_dot_glossary__pb2.KeywordRequest.SerializeToString,
                response_deserializer=app_dot_glossary__pb2.Term.FromString,
                _registered_method=True)
        self.AddTerm = channel.unary_unary(
                '/glossary.GlossaryService/AddTerm',
                request_serializer=app_dot_glossary__pb2.Term.SerializeToString,
                response_deserializer=app_dot_glossary__pb2.Term.FromString,
                _registered_method=True)
        self.UpdateTerm = channel.unary_unary(
                '/glossary.GlossaryService/UpdateTerm',
                request_serializer=app_dot_glossary__pb2.Term.SerializeToString,
                response_deserializer=app_dot_glossary__pb2.Term.FromString,
                _registered_method=True)
        self.DeleteTerm = channel.unary_unary(
                '/glossary.GlossaryService/DeleteTerm',
                request_serializer=app_dot_glossary__pb2.KeywordRequest.SerializeToString,
                response_deserializer=app_dot_glossary__pb2.DeleteResponse.FromString,
                _registered_method=True)


class GlossaryServiceServicer(object):
    """Определение сервиса глоссария
    """

    def GetTerms(self, request, context):
        """1. Получение списка всех терминов
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTerm(self, request, context):
        """2. Получение одного термина по слову
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddTerm(self, request, context):
        """3. Добавление нового термина
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTerm(self, request, context):
        """4. Обновление существующего термина
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteTerm(self, request, context):
        """5. Удаление термина
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GlossaryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTerms': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTerms,
                    request_deserializer=app_dot_glossary__pb2.Empty.FromString,
                    response_serializer=app_dot_glossary__pb2.TermList.SerializeToString,
            ),
            'GetTerm': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTerm,
                    request_deserializer=app_dot_glossary__pb2.KeywordRequest.FromString,
                    response_serializer=app_dot_glossary__pb2.Term.SerializeToString,
            ),
            'AddTerm': grpc.unary_unary_rpc_method_handler(
                    servicer.AddTerm,
                    request_deserializer=app_dot_glossary__pb2.Term.FromString,
                    response_serializer=app_dot_glossary__pb2.Term.SerializeToString,
            ),
            'UpdateTerm': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTerm,
                    request_deserializer=app_dot_glossary__pb2.Term.FromString,
                    response_serializer=app_dot_glossary__pb2.Term.SerializeToString,
            ),
            'DeleteTerm': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteTerm,
                    request_deserializer=app_dot_glossary__pb2.KeywordRequest.FromString,
                    response_serializer=app_dot_glossary__pb2.DeleteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'glossary.GlossaryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('glossary.GlossaryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GlossaryService(object):
    """Определение сервиса глоссария
    """

    @staticmethod
    def GetTerms(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/glossary.GlossaryService/GetTerms',
            app_dot_glossary__pb2.Empty.SerializeToString,
            app_dot_glossary__pb2.TermList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTerm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/glossary.GlossaryService/GetTerm',
            app_dot_glossary__pb2.KeywordRequest.SerializeToString,
            app_dot_glossary__pb2.Term.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddTerm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/glossary.GlossaryService/AddTerm',
            app_dot_glossary__pb2.Term.SerializeToString,
            app_dot_glossary__pb2.Term.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateTerm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/glossary.GlossaryService/UpdateTerm',
            app_dot_glossary__pb2.Term.SerializeToString,
            app_dot_glossary__pb2.Term.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteTerm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/glossary.GlossaryService/DeleteTerm',
            app_dot_glossary__pb2.KeywordRequest.SerializeToString,
            app_dot_glossary__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
